# Generated by Django 5.0.6 on 2024-07-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, unique=True)),
                ('sport', models.CharField(max_length=25)),
                ('team_name', models.CharField(max_length=30, unique=True)),
                ('registraion_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'permissions': [('ultra_register', 'User gets ultra registration')],
            },
        ),
    ]
